version: '3'
services:
  dj-app:
    image: sakr1999/travel-app
    container_name: secand
    build: .

    ports:
      - "8000:8000"
  nginx:
    build: ./nginx
    restart: always

    ports:
      - "8080:80"
    depends_on:
      - dj-app