# Generated by Django 4.1.2 on 2022-11-11 23:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='city',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=20, verbose_name='اسماء المدن')),
                ('country_image', models.ImageField(upload_to='flight/cities')),
            ],
        ),
        migrations.CreateModel(
            name='hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_name', models.CharField(max_length=40, verbose_name=' اسم الفندق')),
                ('address', models.CharField(max_length=50, verbose_name='عنوان الفندق')),
                ('hotel_images', models.ImageField(upload_to='hotel/hotels')),
                ('hotel_star', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('phoneNumber', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('secondPhoneNumber', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('link_comm', models.URLField(verbose_name='الموقع')),
                ('email_comm', models.EmailField(max_length=254, verbose_name='الايميل')),
                ('facebook_comm', models.URLField(verbose_name='صفحة الفيس')),
                ('whatsapp_comm', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('free_cancellation', models.BooleanField(default=True)),
                ('pay_arrival', models.BooleanField(default=True)),
                ('no_smoking', models.BooleanField(default=True)),
                ('allowed_pets', models.BooleanField(default=True)),
                ('include_meals', models.BooleanField(default=True)),
                ('lowest_price', models.IntegerField(default=0)),
                ('amemities_hotel', multiselectfield.db.fields.MultiSelectField(choices=[('Smoking areas', 'Smoking areas'), ('Wi-fi', 'Wi-fi'), ('Air conditioning', 'Air conditioning'), ('Spa', 'Spa'), ('Private beach', 'Private beach'), ('Parking', 'Parking'), ('Airport shuttle', 'Airport shuttle'), ('Pool', 'Pool'), ('Fitness centre', 'Fitness centre'), ('Restaurant', 'Restaurant'), ('Meeting facilities', 'Meeting facilities'), ('Bar', 'Bar'), ('Children pool', 'Children pool'), ('Children facilities', 'Children facilities'), ('Business centre', 'Business centre'), ('Laundry', 'Laundry')], max_length=20)),
                ('kids', models.CharField(max_length=200, verbose_name=' سياسة الاطفال')),
                ('note', models.TextField(max_length=200, verbose_name='ملاحظة')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.city')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=40, verbose_name=' اسم الغرفة')),
                ('room_image', models.ImageField(upload_to='hotel/rooms')),
                ('price', models.IntegerField(default=0, verbose_name='سعرالليلة')),
                ('num_guest', models.IntegerField(default=0, verbose_name='عدد الافراد')),
                ('amemities_room', multiselectfield.db.fields.MultiSelectField(choices=[('Electric kettle', 'Electric kettle'), ('Wi-fi', 'Wi-fi'), ('Air conditioning', 'Air conditioning'), ('Television', 'Television'), ('Telephone', 'Telephone'), ('Shower', 'Shower'), ('Coffee Maker', 'Coffee Maker'), ('Minibar', 'Minibar'), ('Balcony', 'Balcony')], max_length=30)),
                ('room_bed', models.CharField(max_length=100, verbose_name='سراير الغرفة')),
                ('room_food', multiselectfield.db.fields.MultiSelectField(choices=[('1x breakfast', '1x breakfast'), ('2x breakfast', '2x breakfast'), ('1x lunch', '1x lunch'), ('2x lunch', '2x lunch'), ('1x dinner', '1x dinner'), ('2x dinner', '2x dinner')], max_length=20)),
                ('note', models.TextField(max_length=200, verbose_name='ملاحظة')),
                ('hotel_in', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.hotel')),
            ],
        ),
    ]
