# Generated by Django 4.1.2 on 2022-11-11 23:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='apart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='عنوان ')),
                ('apart_images', models.ImageField(upload_to='apartment/aparts')),
                ('amemities_apart', multiselectfield.db.fields.MultiSelectField(choices=[('واي فاي', 'واي فاي'), ('تكيف', 'تكيف'), ('خدمة التنظيف', 'خدمة التنظيف'), ('حراسة امن', 'حراسة امن'), ('غرفة خادمة', 'عرفة خادمة'), ('مسموح بتربية الحيوانات', 'مسموح بتربية الحيوانات'), ('منطقة شواء', 'منطقة شواء'), ('موقف سيارات', 'موقف سيارت'), ('اسانسير', 'اسانسير'), ('شاطي خاص', 'شاطي خاص'), ('بلكونة', 'بلكونة'), ('مسبح خاص', 'مسبح خاص'), ('حديفة خاصة', 'حديقة خاصة'), ('مطلة علي البحيرات', 'مطلة علي البحيرات'), ('مطلة علي البحر', 'مطلة علي البحر')], max_length=100)),
                ('type_apart', multiselectfield.db.fields.MultiSelectField(choices=[('شقة', 'شقة'), ('شالية', 'شالية'), ('فيلا', 'فيلا'), ('بنتهاوس', 'بنتهاوس'), ('دوبلكس', 'دوبلكس'), ('تاون هاوس', 'تاون هاوس'), ('شقق فندقية', 'شقق فندقية'), ('ستوديو', 'ستوديو')], max_length=20)),
                ('address', models.CharField(max_length=50, verbose_name='عنوان الشقة')),
                ('price_night', models.IntegerField(default=0, verbose_name='سعر الليلة')),
                ('price_month', models.IntegerField(default=0, verbose_name='سعر الشهري')),
                ('rooms', models.IntegerField(default=1, verbose_name='عدد الغرف')),
                ('bathroom', models.IntegerField(default=1, verbose_name='عدد الحمامات')),
                ('meter', models.IntegerField(default=1, verbose_name=' المساحة')),
                ('bed', models.IntegerField(default=1, verbose_name=' عدد السراير')),
                ('furniture', models.BooleanField(default=True)),
                ('PhoneNumber', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('whatsapp', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('e_mail', models.EmailField(max_length=254)),
                ('note', models.TextField(verbose_name='ملاحظات')),
            ],
        ),
        migrations.CreateModel(
            name='city',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=20, verbose_name='اسماء المدن')),
                ('city_image', models.ImageField(upload_to='apartment/cities')),
            ],
        ),
        migrations.CreateModel(
            name='town',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('town_name', models.CharField(max_length=20, verbose_name='اسماء المناطق')),
                ('city_in', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apartment.city')),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='apartment/aparts')),
                ('apart', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='apartment.apart')),
            ],
        ),
        migrations.AddField(
            model_name='apart',
            name='the_city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apartment.city'),
        ),
        migrations.AddField(
            model_name='apart',
            name='the_town',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apartment.town'),
        ),
        migrations.AddField(
            model_name='apart',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
