# Generated by Django 4.1.2 on 2022-11-11 23:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='city',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=20, verbose_name='اسماء المدن')),
                ('city_image', models.ImageField(upload_to='wedding/cities')),
            ],
        ),
        migrations.CreateModel(
            name='hall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hall_name', models.CharField(max_length=40, verbose_name=' اسم القاعة')),
                ('address', models.CharField(max_length=50, verbose_name=' عنوان القاعة')),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('price', models.IntegerField(default=0, verbose_name='سعر القاعة')),
                ('number_people', models.IntegerField(default=0, verbose_name='عدد الافراد ')),
                ('price_list', models.TextField(max_length=250, verbose_name='اسعار الاضافات')),
                ('program', models.TextField(max_length=250, verbose_name=':برنامج الفرح ')),
                ('phoneNumber', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('secondPhoneNumber', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('link_hall', models.URLField(verbose_name='الموقع')),
                ('email_hall', models.EmailField(max_length=254, verbose_name='الايميل')),
                ('facebook_hall', models.URLField(verbose_name='صفحة الفيس')),
                ('whatsapp_hall', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('the_city', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='wedding_hall.city')),
            ],
        ),
        migrations.CreateModel(
            name='town',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('town_name', models.CharField(max_length=20, verbose_name='اسماء المناطق')),
                ('city_in', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wedding_hall.city')),
            ],
        ),
        migrations.CreateModel(
            name='hallimage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='wedding/halls')),
                ('hall', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='wedding_hall.hall')),
            ],
        ),
        migrations.AddField(
            model_name='hall',
            name='the_town',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wedding_hall.town'),
        ),
        migrations.AddField(
            model_name='hall',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
